title: FitPulse Pro
description: Training fundamentals and fitness science
theme: minima
baseurl: "/fitpulsepro"
url: "https://siavashsed.github.io"
markdown: kramdown
permalink: /:year/:month/:day/:title/
show_excerpts: true
minima:
  skin: dark
